include:
  - board: nice_nano_v2
    shield: corne_left
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: corne_left_central
  - board: nice_nano_v2
    shield: corne_right
    artifact-name: corne_right_peripheral
