include:
  - board: nice_nano
    shield: corne_custom_left
    # Eliminamos el logging de aquí para que use lo que dice tu .conf
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: corne_custom_left_central
  - board: nice_nano
    shield: corne_custom_right
    artifact-name: corne_custom_right_peripheral
